chore(tool): update `brightness` script
- replace `light` with `brillo`

diff --git a/brightness b/brightness
--- a/brightness
+++ b/brightness
@@ -1,109 +1,111 @@
 #!/usr/bin/env bash
 
-set -e
+# Script for managing brightness
 
-#  ____       _       _     _
-# | __ ) _ __(_) __ _| |__ | |_ _ __   ___  ___ ___
-# |  _ \| '__| |/ _` | '_ \| __| '_ \ / _ \/ __/ __|
-# | |_) | |  | | (_| | | | | |_| | | |  __/\__ \__ \
-# |____/|_|  |_|\__, |_| |_|\__|_| |_|\___||___/___/
-#               |___/
+PROG=$(basename "$0")
+CMD="brillo"
+DEPS=("$CMD" dunstify)
 
-declare -A icons
-path="$HOME/.scripts/icons"
-icons[off]="$path/brightness-off.svg"
-icons[low]="$path/brightness-low.svg"
-icons[medium]="$path/brightness-medium.svg"
-icons[high]="$path/brightness-high.svg"
-
-dependencies() {
-	dependencies=(light)
-	for cmd in "${dependencies[@]}"; do
-		command -v "$cmd" >/dev/null && continue || {
-			echo "$cmd command not found."
-			exit 1
-		}
-	done
-}
-
-get_notification_icon() {
-	current=$(light -G)
-	brightness=${current%.*}
-	if [ "$brightness" -lt "30" ]; then
-		echo "${icons[low]}"
-	elif [ "$brightness" -lt "60" ]; then
-		echo "${icons[medium]}"
-	elif [ "$brightness" -lt "100" ]; then
-		echo "${icons[high]}"
-	elif [ "$brightness" -eq "100" ]; then
-		echo "${icons[high]}"
-	fi
-}
-
-send_notification() {
-	icon=$(get_notification_icon)
-	current=$(light -G)
-	brightness=${current%.*}
-	options="string:x-canonical-private-synchronous:brightness"
-	dunstify -a "Brightness" "Brightness" "Brightness" -i "$icon" -h int:value:"$brightness" -h $options
+get_brightness() {
+	local current
+	current=$("$CMD" -G)
+	echo "${current%.*}"
 }
 
 status_bar() {
+	local icon low mid high brightness
 	low=""
 	mid=""
 	high=""
-	current=$(light -G)
-	brightness=${current%.*}
+	brightness=$(get_brightness)
 
-	printf "%s" "$SEP1"
-	if [ "$brightness" -lt "30" ]; then
+	if [[ "$brightness" -lt "30" ]]; then
 		icon="$low"
-	elif [ "$brightness" -lt "60" ]; then
+	elif [[ "$brightness" -lt "70" ]]; then
 		icon="$mid"
-	elif [ "$brightness" -lt "100" ]; then
-		icon="$high"
-	elif [ "$brightness" -eq "100" ]; then
+  else
 		icon="$high"
 	fi
-	printf "%s %s" "$icon" "$brightness%"
+
+	printf "%s" "$SEP1"
+	printf "%s %s\n" "$icon" "$brightness%"
 	printf "%s" "$SEP2"
-}
-
-increase() {
-	light -A "$1"
-}
-
-decrease() {
-	light -U "$1"
-}
-
-usage() {
-	program=$(basename "$0")
-	echo "$program [OPTIONS] [VALUE]"
-	echo
-	echo "Simple script for managing brightness"
-	echo
-	echo "Usage: $program <increase|decrease>"
-	echo
-	echo "options:"
-	echo " inc		Increase brightness by 5%."
-	echo " dec		Decrease brightness by 5%."
-	echo " -h		Print this Help."
-	echo
 	exit 0
 }
 
-main() {
-	dependencies
+get_notify_icon() {
+	local brightness icon low mid high
+	high=display-brightness-high-symbolic
+	low=display-brightness-low-symbolic
+	mid=display-brightness-medium-symbolic
+	brightness=$(get_brightness)
 
-	case "$1" in
-	inc) increase "${2:-5}" ;;
-	dec) decrease "${2:-5}" ;;
-	status) status_bar ;;
-	*) usage ;;
+	if [[ "$brightness" -lt "30" ]]; then
+		icon="$low"
+	elif [[ "$brightness" -lt "70" ]]; then
+		icon="$mid"
+  else
+		icon="$high"
+	fi
+
+	echo "${icon}"
+}
+
+notify() {
+	local brightness args
+  declare -a args=()
+  args+=(--appname "Brightness" "Brightness" "Brightness")
+  args+=(--icon "$(get_notify_icon)")
+  args+=(--hints string:x-canonical-private-synchronous:brightness)
+  args+=(--hints int:value:"$(get_brightness)")
+  dunstify "${args[@]}"
+}
+
+increase() {
+	"$CMD" -A "$1"
+}
+
+decrease() {
+	"$CMD" -U "$1"
+}
+
+usage() {
+	cat <<-_EOF
+		Usage: $PROG [INC|DEC] [VALUE]
+
+		Simple script for managing brightness
+
+		Options:
+		 -i, inc        Increase brightness by 5%
+		 -d, dec        Decrease brightness by 5%
+		 -s, status     Show current brightness
+		 -h, help       Show this Help
+	_EOF
+	exit
+}
+
+main() {
+  local option
+  option="$1"
+
+	for cmd in "${DEPS[@]}"; do
+		if ! command -v "$cmd" >/dev/null; then
+			echo "$PROG: '$cmd' command not found."
+			exit 1
+		fi
+	done
+
+  shift 
+
+	case "$option" in
+	-i | inc) increase "${1:-3}" ;;
+	-d | dec) decrease "${1:-3}" ;;
+	-s | status) status_bar ;;
+  -h | help | --help) usage ;;
+	*) status_bar ;;
 	esac
 
-	send_notification
+	notify
 }
 
 main "$1" "$2"
