feat: add/updates scripts

diff --git a/mailto b/mailto
--- a/mailto
+++ b/mailto
@@ -1,63 +1,101 @@
 #!/usr/bin/env bash
 
 PROG=$(basename "$0")
-MUTT="$XDG_CONFIG_HOME/mutt"
+SHELL=${SHELL:-$(which zsh)}
+TERMINAL=${TERMINAL:-st}
+MUTT="${XDG_CONFIG_HOME:-$HOME/.config}/mutt"
+declare -a ACCOUNTS
 
-function log_err_and_exit {
-	echo "$PROG: $*"
-	exit 1
+# colors
+BLUE="#5f819d"
+WHITE="#f8f8f2"
+
+# menu
+MENU="dmenu"
+declare -a MENU_ARGS=(-i -l 10)
+
+function usage {
+    echo "usage: $PROG <email>"
 }
 
-function get_acc_file() {
-	local choice="$1"
-	local account_name=$(find "$MUTT/accounts" -name "*$choice*")
-
-	echo "$account_name"
+function logerr_exit {
+    printf "%s: %s\n" "$PROG" "$*" >&2
+    exit 1
 }
 
-function launch_email_client() {
-	local account_file account_name send_to
-	account_name="$1"
-	send_to="$2"
-	account_file=$(get_acc_file "$account_name")
+function accounts_load {
+    local path files
+    path="$MUTT/accounts"
+    files=$(cd "$path" && find . | tail -n +2 | sed "s/\.\///g; s/\.muttrc$//g")
 
-	setsid "$TERMINAL" -e neomutt "$send_to" -F "$MUTT/muttrc" -F "$account_file"
-	exit 0
+    [[ -z "$files" ]] && logerr_exit "no accounts found in $path"
+
+    IFS=$'\n' readarray -t ACCOUNTS <<<"$files"
 }
 
-function select_acc {
-	local accounts choice
-	accounts="$*"
-	choice=$(echo "$accounts" | dmenu -i -l "$(echo "$accounts" | wc -l)" -p "send from>")
+function accounts_getfile {
+    local choice="$1"
+    local account_name
+    account_name=$(find "$MUTT/accounts" -name "*$choice*")
 
-	echo "$choice"
+    echo "$account_name"
 }
 
-function main() {
-	local send_to choice accounts account_file
+function account_select {
+    local choice
+    MENU_ARGS+=(-p " Sender>")
+    MENU_ARGS+=(-sb "$BLUE" -sf "$WHITE")
+    choice=$(printf "%s\n" "${ACCOUNTS[@]}" | "$MENU" "${MENU_ARGS[@]}")
 
-	accounts=$(cd "$MUTT/accounts" && find . | tail -n +2 | sed "s/\.\///g; s/\.muttrc$//g")
-	send_to="$*"
+    echo "$choice"
+}
 
-	if [[ "${#accounts[@]}" -eq 0 ]]; then
-		log_err_and_exit "no accounts found in $MUTT/accounts"
-	fi
+function run_email_client {
+    local account_file account_name send_to
+    account_name="$1"
+    send_to="$2"
+    account_file=$(accounts_getfile "$account_name")
 
-	if [[ "${#accounts[@]}" -eq 1 ]]; then
-		launch_email_client "${accounts[@]}" "$send_to"
-	fi
+    [[ -z "$account_file" ]] && logerr_exit "account '$account_name' not found"
 
-	choice=$(select_acc "$accounts")
+    setsid -f "$TERMINAL" -e neomutt "$send_to" -F "$MUTT/muttrc" -F "$account_file"
+}
 
-	[[ -z "$choice" ]] && exit
+function dependencies {
+    declare -a deps=(neomutt setsid dmenu)
+    for dep in "${deps[@]}"; do
+        if ! command -v "$dep" >/dev/null; then
+            logerr_exit "'$dep' not found"
+        fi
+    done
 
-	account_file=$(get_acc_file "$choice")
+}
 
-	if [[ "$account_file" == "" ]]; then
-		log_err_and_exit "account '$choice' not found"
-	fi
+function main {
+    dependencies
+    local sendto="$1"
+    local account_path=$MUTT/accounts
+    if [[ ! -d "$account_path" ]]; then
+        logerr_exit "no mutt accounts found in $account_path"
+    fi
 
-	launch_email_client "$choice" "$send_to"
+    [[ -z "$sendto" ]] && {
+        usage
+        exit 1
+    }
+
+    accounts_load
+
+    if [[ "${#ACCOUNTS[@]}" -eq 1 ]]; then
+        run_email_client "${ACCOUNTS[@]}" "$sendto"
+        return 0
+    fi
+
+    local account_chose
+    account_chose=$(account_select)
+    [[ -z "$account_chose" ]] && logerr_exit "no account selected"
+
+    run_email_client "$account_chose" "$sendto"
 }
 
 main "$@"
diff --git a/microphone b/microphone
--- a/microphone
+++ b/microphone
@@ -1,5 +1,9 @@
 #!/usr/bin/env bash
 
+# ╻ ╻╻┏━┓
+# ┃╻┃┃┣━┛
+# ┗┻┛╹╹
+#
 # Simple script checks the current state of the
 # external microphone and toggle state (mute/unmute)
 
@@ -28,233 +32,230 @@ NOTIFY_ENABLE="audio-input-microphone-symbolic"
 NOTIFY_DISABLE="microphone-sensitivity-muted-symbolic"
 NOTIFY_ERR="dialog-error-symbolic"
 
-function usage() {
-	printf "%s\n" "Usage: $PROG [OPTIONS]
+function usage {
+    cat <<-_EOF
+Usage: $PROG [OPTIONS]
 
 Options:
-  -s, status        Show microphone status
-  -e, enable        Enable microphone
-  -d, disable       Disable microphone
-  -t, toggle        Toggle microphone status
-  -c, captures      List available captures"
-	exit 0
+    -s, status        Show microphone status
+    -e, enable        Enable microphone
+    -d, disable       Disable microphone
+    -t, toggle        Toggle microphone status
+    -c, captures      List available captures
+_EOF
+    exit 0
 }
 
-function log_error() {
-	printf "%s: %s\n" "$PROG" "$*" >&2
-	exit 1
+function log_error {
+    printf "%s: %s\n" "$PROG" "$*" >&2
+    exit 1
 }
 
-function log_msg() {
-	printf "%s: %s\n" "$PROG" "$*"
+function log_msg {
+    printf "%s: %s\n" "$PROG" "$*"
 }
 
-function notify() {
-	local icon title mesg args
-	icon="$1"
-	title="$2"
-	mesg="$3"
-	declare -a args=(--appname="$PROG")
-	args+=(--icon "$icon" --timeout 3000)
-	args+=(--hints string:x-dunst-stack-tag:microphone)
-	dunstify "${args[@]}" "$title" "$mesg"
+function notify {
+    local icon title mesg args
+    icon="$1"
+    title="$2"
+    mesg="$3"
+    declare -a args=(--appname="$PROG")
+    args+=(--icon "$icon" --timeout 3000)
+    args+=(--hints string:x-dunst-stack-tag:microphone)
+    dunstify "${args[@]}" "$title" "$mesg"
 }
 
-function is_connected() {
-	local card="$1"
-	local mic="$2"
+function is_connected {
+    local card="$1"
+    local mic="$2"
 
-	amixer -c "$card" get "$mic" &>/dev/null
-	local retcode=$?
-	if [[ $retcode -eq 0 ]]; then
-		return 0
-	fi
-	return 1
+    amixer -c "$card" get "$mic" &>/dev/null
+    local retcode=$?
+    if [[ $retcode -eq 0 ]]; then
+        return 0
+    fi
+    return 1
 }
 
-function get_capture() {
-	local arg name data
-	name="$1"
+function get_capture {
+    local arg name data
+    name="$1"
 
-	if [[ "$#" -eq 0 ]]; then
-		log_error "usage: get_capture [capture]"
-	fi
+    if [[ "$#" -eq 0 ]]; then
+        log_error "usage: get_capture [capture]"
+    fi
 
-	arg=$(echo "$name" | tr '[:upper:]' '[:lower:]')
-	data="${CAPTURES[$arg]}"
+    arg=$(echo "$name" | tr '[:upper:]' '[:lower:]')
+    data="${CAPTURES[$arg]}"
 
-	if [[ -z "$data" ]]; then
-		log_error "unknown capture '$name'"
-	fi
+    if [[ -z "$data" ]]; then
+        log_error "unknown capture '$name'"
+    fi
 
-	echo "$data"
+    echo "$data"
 }
 
-function power_on() {
-	local card="$1"
-	local mic="$2"
+function is_power_on {
+    local card="$1"
+    local mic="$2"
 
-	if ! is_connected "$card" "$mic"; then
-		return 1
-	fi
+    if ! is_connected "$card" "$mic"; then
+        return 1
+    fi
 
-	mic_status=$(amixer -c "$card" get "$mic" | grep "Front Left:" | awk '{print $7}')
-	if [[ "$mic_status" != "[on]" ]]; then
-		return 1
-	fi
+    mic_status=$(amixer -c "$card" get "$mic" | grep "Front Left:" | awk '{print $7}')
+    if [[ "$mic_status" != "[on]" ]]; then
+        return 1
+    fi
 
-	return 0
+    return 0
 }
 
-function status() {
-	local msg="microphone ${YELLOW}$MIC_EXT_NAME${RESET} is "
-	if power_on "${MIC_EXT[@]}"; then
-		msg+="${GREEN}enabled"
-	else
-		msg+="${RED}disable"
-	fi
-	log_msg "$msg"
+function status {
+    local msg="microphone ${YELLOW}$MIC_EXT_NAME${RESET} is "
+    if is_power_on "${MIC_EXT[@]}"; then
+        msg+="${GREEN}enabled"
+    else
+        msg+="${RED}disable"
+    fi
+    log_msg "$msg"
 }
 
-function status-beta() {
-	local capture data card mic msg
+function status-beta {
+    local capture data card mic msg
 
-	log_msg "checking captures status..."
-	for capture in "${!CAPTURES[@]}"; do
-		data="$(get_capture "$capture")"
-		card=${data%% *}
-		mic=${data##* }
-		printf "  - %s: " "$capture"
+    log_msg "checking captures status..."
+    for capture in "${!CAPTURES[@]}"; do
+        data="$(get_capture "$capture")"
+        card=${data%% *}
+        mic=${data##* }
+        printf "  - %s: " "$capture"
 
-		if power_on "$card" "$mic"; then
-			echo "${GREEN}enabled${RESET}"
-		else
-			echo "${RED}disable${RESET}"
-		fi
-	done
+        if is_power_on "$card" "$mic"; then
+            echo "${GREEN}enabled${RESET}"
+        else
+            echo "${RED}disable${RESET}"
+        fi
+    done
 }
 
-function toggle-micro() {
-	local name capture card mic
-	name="$1"
+function toggle-micro {
+    local name capture card mic
+    name="$1"
 
-	if [ "$#" -eq 0 ]; then
-		log_error "usage: toggle [capture]"
-	fi
+    if [[ "$#" -eq 0 ]]; then
+        log_error "usage: toggle [capture]"
+    fi
 
-	# capture=$(get_capture "$name")
-	# retcode=$?
-	# if [ $retcode -ne 0 ]; then
-	# 	log_error "unknown capture '$1'"
-	# fi
+    # capture=$(get_capture "$name")
+    # retcode=$?
+    # if [ $retcode -ne 0 ]; then
+    # 	log_error "unknown capture '$1'"
+    # fi
 
-	if ! get_capture "$name" >/dev/null; then
-		log_error "unknown capture '$1'"
-	fi
+    if ! get_capture "$name" >/dev/null; then
+        log_error "unknown capture '$1'"
+    fi
 
-	capture=$(get_capture "$name")
-	card=${capture%% *}
-	mic=${capture##* }
+    capture=$(get_capture "$name")
+    card=${capture%% *}
+    mic=${capture##* }
 
-	if ! is_connected "$card" "$mic"; then
-		local err_msg="'$name' not found"
-		notify "${NOTIFY_ERR}" "toggle" "${err_msg}"
-		log_error "${err_msg}"
-	fi
+    if ! is_connected "$card" "$mic"; then
+        local err_msg="'$name' not found"
+        notify "${NOTIFY_ERR}" "toggle" "${err_msg}"
+        log_error "${err_msg}"
+    fi
 
-	if power_on "$card" "$mic"; then
-		notify "$NOTIFY_DISABLE" "🔴 $PROG" "Microphone '$name' Disable"
-	else
-		notify "$NOTIFY_ENABLE" "🟢 $PROG" "Microphone '$name' Enable"
-	fi
+    if is_power_on "$card" "$mic"; then
+        notify "$NOTIFY_DISABLE" "🔴 $PROG" "Microphone '$name' Disable"
+    else
+        notify "$NOTIFY_ENABLE" "🟢 $PROG" "Microphone '$name' Enable"
+    fi
 
-	amixer -c "$card" sset "$mic" toggle &>/dev/null
+    amixer -c "$card" sset "$mic" toggle &>/dev/null
 }
 
-function available() {
-	local msg="Available captures:"
-
-	for cap in "${!CAPTURES[@]}"; do
-		msg+=" 
-  - $cap"
-	done
-
-	echo "$msg"
+function available {
+    local msg="Available captures:"
+    printf "\n"
+    printf "  %s\n" "${CAPTURES[@]}"
 }
 
-function disable-micro() {
-	local name data card mic
-	name="$1"
+function disable-micro {
+    local name data card mic
+    name="$1"
 
-	if [ "$#" -eq 0 ]; then
-		log_error "usage: disable [capture]"
-	fi
+    if [[ "$#" -eq 0 ]]; then
+        log_error "usage: disable [capture]"
+    fi
 
-	data="$(get_capture "$name")"
-	card=${data%% *}
-	mic=${data##* }
+    data="$(get_capture "$name")"
+    card=${data%% *}
+    mic=${data##* }
 
-	if ! is_connected "$card" "$mic"; then
-		local err_msg="'$name' not found"
-		notify "${NOTIFY_ERR}" "disable" "${err_msg}"
-		log_error "${err_msg}"
-	fi
+    if ! is_connected "$card" "$mic"; then
+        local err_msg="'$name' not found"
+        notify "${NOTIFY_ERR}" "disable" "${err_msg}"
+        log_error "${err_msg}"
+    fi
 
-	if ! power_on "$card" "$mic"; then
-		log_error "'$name' already disable"
-	fi
+    if ! is_power_on "$card" "$mic"; then
+        log_error "'$name' already disable"
+    fi
 
-	amixer -c "$card" set "$mic" nocap &>/dev/null
-	notify "$NOTIFY_DISABLE" "🔴 $PROG" "Microphone '$1' Disable"
+    amixer -c "$card" set "$mic" nocap &>/dev/null
+    notify "$NOTIFY_DISABLE" "🔴 $PROG" "Microphone '$1' Disable"
 }
 
-function enable-micro() {
-	local name data card mic
+function enable-micro {
+    local name data card mic
 
-	if [ "$#" -eq 0 ]; then
-		log_error "usage: enable [capture]"
-	fi
+    if [[ "$#" -eq 0 ]]; then
+        log_error "usage: enable [capture]"
+    fi
 
-	name="$1"
-	data="$(get_capture "$name")"
-	card=${data%% *}
-	mic=${data##* }
+    name="$1"
+    data="$(get_capture "$name")"
+    card=${data%% *}
+    mic=${data##* }
 
-	if ! is_connected "$card" "$mic"; then
-		local err_msg="'$name' not found"
-		notify "${NOTIFY_ERR}" "enable" "${err_msg}"
-		log_error "${err_msg}"
-	fi
+    if ! is_connected "$card" "$mic"; then
+        local err_msg="'$name' not found"
+        notify "${NOTIFY_ERR}" "enable" "${err_msg}"
+        log_error "${err_msg}"
+    fi
 
-	if power_on "$card" "$mic"; then
-		log_error "'$1' already enable"
-	fi
+    if is_power_on "$card" "$mic"; then
+        log_error "'$1' already enable"
+    fi
 
-	amixer -c "$card" set "$mic" cap &>/dev/null
-	notify "$NOTIFY_ENABLE" "🟢 $PROG" "Microphone '$1' Enable"
+    amixer -c "$card" set "$mic" cap &>/dev/null
+    notify "$NOTIFY_ENABLE" "🟢 $PROG" "Microphone '$1' Enable"
 }
 
-function main() {
-	# Always disable built-in microphone
-	if power_on "${MIC_INTERNAL[@]}"; then
-		disable-micro "internal" "${MIC_INTERNAL[@]}"
-	fi
+function main {
+    # Always disable built-in microphone
+    if is_power_on "${MIC_INTERNAL[@]}"; then
+        disable-micro "internal" "${MIC_INTERNAL[@]}"
+    fi
 
-	case "$1" in
-	-s | status) status-beta ;;
-	-t | toggle) shift && toggle-micro "$@" ;;
-	-e | enable) shift && enable-micro "$@" ;;
-	-d | disable) shift && disable-micro "$@" ;;
-	-c | captures) log_msg "$(available)" ;;
-	*) usage ;;
-	esac
+    case "$1" in
+    -s | status) status-beta ;;
+    -t | toggle) shift && toggle-micro "$@" ;;
+    -e | enable) shift && enable-micro "$@" ;;
+    -d | disable) shift && disable-micro "$@" ;;
+    -c | captures) log_msg "$(available)" ;;
+    *) usage ;;
+    esac
 }
 
 for dep in "${DEPS[@]}"; do
-	if ! command -v "$dep" >/dev/null; then
-		notify "$NOTIFY_ERR" "$PROG" "$dep not found"
-		log_error "$dep not found"
-	fi
+    if ! command -v "$dep" >/dev/null; then
+        notify "$NOTIFY_ERR" "$PROG" "$dep not found"
+        log_error "$dep not found"
+    fi
 done
 
 main "$@"
diff --git a/ytmpv b/ytmpv
--- a/ytmpv
+++ b/ytmpv
@@ -6,82 +6,81 @@
 # example:
 #   $ ytmpv "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
 #
-# description: play a video from a given url using mpv with notifications and logging.
-# author: @haaag
-# version: 0.1
+# play a video from a given url using mpv with notifications and logging.
 
 set -o errexit
 set -o pipefail
 
 PROG=$(basename "$0")
-DEPS=(mpv curl perl)
-LOGGER="${LOG_PATH:-$HOME/docs/log}/${PROG}.log"
+DEPS=(mpv curl perl mpvc mpvqueue)
+LOGGER="${LOGS_PATH:-$HOME/docs/log}/${PROG}.log"
 XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
 
-create_file() {
-	local file="$1"
-	touch "$file"
-	sleep 1
+function create_file {
+    local file="$1"
+    touch "$file"
+    sleep 1
 }
 
-log_err() {
-	printf "%s: %s\n" "$PROG" "$*" >&2
-	exit 1
+function log_err {
+    printf "%s: %s\n" "$PROG" "$*" >&2
+    exit 1
 }
 
-check_dependencies() {
-	for cmd in "${DEPS[@]}"; do
-		if ! command -v "$cmd" >/dev/null; then
-			log_err "dependency '$cmd' not found"
-		fi
-	done
+function check_dependencies {
+    for cmd in "${DEPS[@]}"; do
+        if ! command -v "$cmd" >/dev/null; then
+            log_err "dependency '$cmd' not found"
+        fi
+    done
 }
 
-log_mesg() {
-	local title="$1"
-	local url="$2"
-	echo "[$(date '+%F %T')]::[$PROG]::${title}::[URL]::${url}" | tee -a "$LOGGER" >/dev/null
+function log_mesg {
+    local title="$1"
+    local url="$2"
+    echo "[$(date '+%F %T')]::[$PROG]::${title}::[URL]::${url}" | tee -a "$LOGGER" >/dev/null
 }
 
-notification() {
-	local mesg="Launching: $1"
-	notify-send "$PROG" "$mesg"
+function notification {
+    local mesg="Launching: $1"
+    notify-send "$PROG" "$mesg"
 }
 
-open_mpv() {
-	setsid mpv --input-ipc-server="${MPVSOCKET:-/tmp/mpvsocket}" -quiet "$1" >/dev/null 2>&1 &
+function open_mpv {
+    setsid -f mpv --input-ipc-server="${MPVSOCKET:-/tmp/mpvsocket}" -quiet "$1" >/dev/null 2>&1 &
 }
 
-usage() {
-	cat <<-_EOF
-		Usage: $PROG <URL>
-	_EOF
-	exit
+function usage {
+    cat <<-_EOF
+Usage: $PROG <URL>
+_EOF
+    exit
 }
 
-main() {
-	local url video_title
-	if [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
-		usage
-	fi
+function main {
+    local url video_title
+    if [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
+        usage
+    fi
 
-	check_dependencies
+    check_dependencies
 
-	url="$1"
-	[[ -z "$url" ]] && log_err "no <URL> found"
+    url="$1"
+    [[ -z "$url" ]] && log_err "no <URL> found"
 
-	if ! curl -sL -I "$url" >/dev/null 2>&1; then
-		log_err "failed to retrieve the URL: '$url'"
-	fi
+    if ! curl -sL -I "$url" >/dev/null 2>&1; then
+        log_err "failed to retrieve the URL: '$url'"
+    fi
 
-	video_title=$(curl -sL "$url" | perl -l -0777 -ne 'print $1 if /<title.*?>\s*(.*?)\s*<\/title/si')
-	if [[ -z "$video_title" ]]; then
-		video_title="err: failed to extract video title."
-	fi
+    video_title=$(curl -sL "$url" | perl -l -0777 -ne 'print $1 if /<title.*?>\s*(.*?)\s*<\/title/si')
+    if [[ -z "$video_title" ]]; then
+        video_title="err: failed to extract video title."
+    fi
 
-	log_mesg "$video_title" "$url"
-	open_mpv "$url"
-	notification "$video_title"
+    log_mesg "$video_title" "$url"
+    # open_mpv "$url"
+    setsid -f mpvqueue "$url" &
+    notification "$video_title"
 }
 
 main "$@"
