feat(bar): updates

diff --git a/bar/bar-devices b/bar/bar-devices
--- a/bar/bar-devices
+++ b/bar/bar-devices
@@ -1,59 +1,66 @@
 #!/usr/bin/env bash
 
+# ╻ ╻╻┏━┓
+# ┃╻┃┃┣━┛
+# ┗┻┛╹╹
+#
+# Script for displaying audio status in dwm bar.
+#
 # Output: ${NORMAL} || ${MUTED} || ""
+
 EXTERNAL_MIC=(2 Mic)
 NORMAL=""
 MUTED=""
 
-function mic_is_connected() {
-	local channel mic
-	channel="$1"
-	mic="$2"
+function mic_is_connected {
+    local channel mic
+    channel="$1"
+    mic="$2"
 
-	amixer -c "$channel" get "$mic" &>/dev/null
-	exit_status=$?
-	if [[ $exit_status -eq 0 ]]; then
-		return 0
-	fi
+    amixer -c "$channel" get "$mic" &>/dev/null
+    exit_status=$?
+    if [[ $exit_status -eq 0 ]]; then
+        return 0
+    fi
 
-	return 1
+    return 1
 }
 
-function power_on() {
-	local channel mic
-	channel="$1"
-	mic="$2"
+function power_on {
+    local channel mic
+    channel="$1"
+    mic="$2"
 
-	if ! mic_is_connected "$channel" "$mic"; then
-		exit 1
-	fi
+    if ! mic_is_connected "$channel" "$mic"; then
+        exit 1
+    fi
 
-	mic_status=$(amixer -c "$channel" get "$mic" | grep "Front Left:" | awk '{print $7}')
-	if [[ "$mic_status" == "[on]" ]]; then
-		return 0
-	fi
+    mic_status=$(amixer -c "$channel" get "$mic" | grep "Front Left:" | awk '{print $7}')
+    if [[ "$mic_status" == "[on]" ]]; then
+        return 0
+    fi
 
-	return 1
+    return 1
 }
 
-function main() {
-	local output=""
+function main {
+    local output=""
 
-	if ! command -v amixer >/dev/null; then
-		printf "%s: %s\n" "$(basename "$0")" "'amixer' not found"
-		exit 1
-	fi
+    if ! command -v amixer >/dev/null; then
+        printf "%s: %s\n" "$(basename "$0")" "'amixer' not found"
+        exit 1
+    fi
 
-	if mic_is_connected "${EXTERNAL_MIC[@]}"; then
-		if power_on "${EXTERNAL_MIC[@]}"; then
-			output="$output $NORMAL"
-		else
-			output="$output $MUTED"
-		fi
-	fi
-	printf "%s" "$SEP1"
-	printf "%s" "$output"
-	printf "%s" "$SEP2"
+    if mic_is_connected "${EXTERNAL_MIC[@]}"; then
+        if power_on "${EXTERNAL_MIC[@]}"; then
+            output="$output $NORMAL"
+        else
+            output="$output $MUTED"
+        fi
+    fi
+    printf "%s" "${SEP1:-}"
+    printf "%s" "$output"
+    printf "%s" "${SEP2:-}"
 }
 
 main
diff --git a/bar/bar-volume b/bar/bar-volume
--- a/bar/bar-volume
+++ b/bar/bar-volume
@@ -1,18 +1,12 @@
 #!/usr/bin/env bash
 
+# Script for displaying volume status in dwm bar.
+#
+# Output: [ICON 55%]
+
 PROG=$(basename "$0")
 ICON_BAR=""
 ICON_NOTIFY=""
-
-if ! command -v wpctl >/dev/null; then
-	err="'wpctl' not found"
-	printf "%s: %s\n" "$PROG" "$err"
-	notify-send "$PROG" "$err"
-	exit 1
-fi
-
-VOL=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2}')
-VOL=$(awk "BEGIN { printf \"%.0f\n\", $VOL * 100 }")
 
 # bar icons
 low_icon=""
@@ -27,58 +21,57 @@ noti_high_icon="audio-volume-high-symbolic"
 noti_over_icon="audio-volume-overamplified-symbolic"
 noti_muted_icon="audio-volume-muted-symbolic"
 
-function is_muted() {
-	local status
-	status=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
+if ! command -v wpctl >/dev/null; then
+    err="'wpctl' not found"
+    printf "%s: %s\n" "$PROG" "$err"
+    notify-send "$PROG" "$err"
+    exit 1
+fi
 
-	if [[ "${status}" =~ "MUTED" ]]; then
-		return 0
-	fi
+VOL=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2}')
+VOL=$(awk "BEGIN { printf \"%.0f\n\", $VOL * 100 }")
 
-	return 1
+function is_muted {
+    local status
+    status=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
+
+    if [[ "${status}" =~ "MUTED" ]]; then
+        return 0
+    fi
+
+    return 1
 }
 
-function load_icons() {
-	if is_muted || [[ "$VOL" -eq 0 ]]; then
-		ICON_BAR="$muted_icon"
-		ICON_NOTIFY="$noti_muted_icon"
-	elif [[ "$VOL" -gt 0 && "$VOL" -le 15 ]]; then
-		ICON_BAR="$low_icon"
-		ICON_NOTIFY="$noti_low_icon"
-	elif [[ "$VOL" -gt 16 && "$VOL" -le 65 ]]; then
-		ICON_BAR="$mid_icon"
-		ICON_NOTIFY="$noti_med_icon"
-	elif [[ "$VOL" -gt 66 && "$VOL" -le 100 ]]; then
-		ICON_BAR="$high_icon"
-		ICON_NOTIFY="$noti_high_icon"
-	else
-		ICON_BAR="$high_icon"
-		ICON_NOTIFY="$noti_over_icon"
-	fi
+function load_icons {
+    if is_muted || [[ "$VOL" -eq 0 ]]; then
+        ICON_BAR="$muted_icon"
+        ICON_NOTIFY="$noti_muted_icon"
+    elif [[ "$VOL" -gt 0 && "$VOL" -le 15 ]]; then
+        ICON_BAR="$low_icon"
+        ICON_NOTIFY="$noti_low_icon"
+    elif [[ "$VOL" -gt 16 && "$VOL" -le 65 ]]; then
+        ICON_BAR="$mid_icon"
+        ICON_NOTIFY="$noti_med_icon"
+    elif [[ "$VOL" -gt 66 && "$VOL" -le 100 ]]; then
+        ICON_BAR="$high_icon"
+        ICON_NOTIFY="$noti_high_icon"
+    else
+        ICON_BAR="$high_icon"
+        ICON_NOTIFY="$noti_over_icon"
+    fi
 }
 
-function notify-vol() {
-	local icon="$1"
-	local appname="Volume"
-	local hints="string:x-canonical-private-synchronous:volume"
-	dunstify -a "$appname" "$appname" "$appname: " -i "$icon" -h int:value:"$VOL" -h "${hints}"
+function notify-vol {
+    local icon="$1"
+    local appname="Volume"
+    local hints="string:x-canonical-private-synchronous:volume"
+    dunstify -a "$appname" "$appname" "$appname: " -i "$icon" -h int:value:"$VOL" -h "${hints}"
 }
 
-function main() {
-	load_icons
-
-	# case 1 in
-	# $((VOL >= 70))) ICON_BAR=$high_icon ICON_NOTIFY=$noti_high_icon ;;
-	# $((VOL >= 30))) ICON_BAR=$mid_icon ICON_NOTIFY=$noti_med_icon ;;
-	# $((VOL >= 1))) ICON_BAR=$low_icon ICON_NOTIFY=$noti_low_icon ;;
-	# *) echo "$muted_icon" && exit ;;
-	# esac
-
-	printf "%s" "$SEP1"
-	printf "%s  %s%%" "$ICON_BAR" "$VOL"
-	printf "%s\n" "$SEP2"
-
-	notify-vol "$ICON_NOTIFY"
+function main {
+    load_icons
+    printf "%s%s  %s%%%s\n" "${SEP1:-}" "$ICON_BAR" "$VOL" "${SEP2:-}"
+    notify-vol "$ICON_NOTIFY"
 }
 
 main
diff --git a/bar/bar-weather b/bar/bar-weather
--- a/bar/bar-weather
+++ b/bar/bar-weather
@@ -1,14 +1,31 @@
 #!/usr/bin/env bash
 
+# Script to display weather information in the dwm bar.
+#
+# Requires: jq curl
+# Optional: notify-send
+# Output: [TEMPICON 14°C HUMIDITY 77%]
+
 PROG=$(basename "$0")
 DEPS=(jq curl)
 HUMIDITY=""
 #      
 
-function log_err() {
-  printf "%s: %s\n" "$PROG" "$@"
-  notify-send -i dialog-error-symbolic "$PROG" "$@"
-  exit 1
+function notification {
+    local date icon
+    date=$(date +"%a, %H:%M")
+    icon="${ICONS}${2}.png"
+    if command -v notify-send >/dev/null; then
+        notify-send -i "$icon" "Weather $date" "$1"
+    fi
+}
+
+function log_err {
+    printf "%s: %s\n" "$PROG" "$@"
+    if command -v notify-send >/dev/null; then
+        notify-send -i dialog-error-symbolic "$PROG" "$@"
+    fi
+    exit 1
 }
 
 # load envs
@@ -16,117 +33,110 @@ function log_err() {
 [[ -f "$PRIVATE_ROOT"/openweather ]] && source "$PRIVATE_ROOT"/openweather
 
 if [[ -z "$OPEN_WEATHERMAP_KEY" ]]; then
-  log_err "openweather api not found."
+    log_err "openweather api not found."
 fi
 
 TOKEN="$OPEN_WEATHERMAP_KEY"
 CITY="$OPEN_WEATHERMAP_CITY"
 UNITS="metric"
 API="https://api.openweathermap.org/data/2.5"
-ICONS="$SCRIPTS/icons/weather/"
+ICONS="${SCRIPTS:-$HOME/.scripts}/icons/weather/"
 GEOCLUE="https://location.services.mozilla.com/v1/geolocate?key=geoclue"
 
-function get_icon() {
-  case $1 in
-  01d) icon="" ;;
-  01n) icon="" ;;
-  02d) icon="" ;;
-  02n) icon="" ;;
-  03*) icon="" ;;
-  04*) icon="" ;;
-  09*) icon="" ;;
-  10d) icon="" ;;
-  10n) icon="" ;;
-  11d) icon="" ;;
-  11n) icon="" ;;
-  13*) icon="" ;;
-  50*) icon="" ;;
-  *) icon="" ;;
-  esac
+function get_icon {
+    case $1 in
+    01d) icon="" ;;
+    01n) icon="" ;;
+    02d) icon="" ;;
+    02n) icon="" ;;
+    03*) icon="" ;;
+    04*) icon="" ;;
+    09*) icon="" ;;
+    10d) icon="" ;;
+    10n) icon="" ;;
+    11d) icon="" ;;
+    11n) icon="" ;;
+    13*) icon="" ;;
+    50*) icon="" ;;
+    *) icon="" ;;
+    esac
 
-  echo "$icon "
+    echo "$icon "
 }
 
-function get_location() {
-  local location
-  location=$(curl -sf "$GEOCLUE")
-  if [[ -n "$location" ]]; then
-    location_lat="$(echo "$location" | jq '.location.lat')"
-    location_lon="$(echo "$location" | jq '.location.lng')"
-    weather=$(curl -sf "$API/weather?appid=$TOKEN&lat=$location_lat&lon=$location_lon&units=$UNITS")
-    weather_icon=$(echo "$weather" | jq -r ".weather[0].icon")
-  fi
-}
-
-function get_weather() {
-  # FIX: Split me...
-  if [[ -n "$CITY" ]]; then
-
-    # If is cityID
-    if [[ "$CITY" -eq "$CITY" ]] 2>/dev/null; then
-      city_param="id=$CITY"
-    else
-      city_param="q=$CITY"
-    fi
-
-    weather=$(curl -sf "$API/weather?appid=$TOKEN&$city_param&units=$UNITS")
-    weather_icon=$(echo "$weather" | jq -r ".weather[0].icon")
-  else
+function get_location {
+    local location
     location=$(curl -sf "$GEOCLUE")
     if [[ -n "$location" ]]; then
-      location_lat="$(echo "$location" | jq '.location.lat')"
-      location_lon="$(echo "$location" | jq '.location.lng')"
-      weather=$(curl -sf "$API/weather?appid=$TOKEN&lat=$location_lat&lon=$location_lon&units=$UNITS")
-      weather_icon=$(echo "$weather" | jq -r ".weather[0].icon")
-      echo -e "$API/weather?appid=$TOKEN&lat=$location_lat&lon=$location_lon&units=$UNITS"
+        location_lat="$(echo "$location" | jq '.location.lat')"
+        location_lon="$(echo "$location" | jq '.location.lng')"
+        weather=$(curl -sf "$API/weather?appid=$TOKEN&lat=$location_lat&lon=$location_lon&units=$UNITS")
+        weather_icon=$(echo "$weather" | jq -r ".weather[0].icon")
     fi
-  fi
 }
 
-function notification() {
-  local date icon
-  date=$(date +"%a, %H:%M")
-  icon="${ICONS}${2}.png"
-  notify-send -i "$icon" "Weather $date" "$1"
+function get_weather {
+    # FIX: Split me...
+    if [[ -n "$CITY" ]]; then
+
+        # If is cityID
+        if [[ "$CITY" -eq "$CITY" ]] 2>/dev/null; then
+            city_param="id=$CITY"
+        else
+            city_param="q=$CITY"
+        fi
+
+        weather=$(curl -sf "$API/weather?appid=$TOKEN&$city_param&units=$UNITS")
+        weather_icon=$(echo "$weather" | jq -r ".weather[0].icon")
+    else
+        location=$(curl -sf "$GEOCLUE")
+        if [[ -n "$location" ]]; then
+            location_lat="$(echo "$location" | jq '.location.lat')"
+            location_lon="$(echo "$location" | jq '.location.lng')"
+            weather=$(curl -sf "$API/weather?appid=$TOKEN&lat=$location_lat&lon=$location_lon&units=$UNITS")
+            weather_icon=$(echo "$weather" | jq -r ".weather[0].icon")
+            echo -e "$API/weather?appid=$TOKEN&lat=$location_lat&lon=$location_lon&units=$UNITS"
+        fi
+    fi
 }
 
-function dwm_weather() {
-  local icon desc temp humidity message
-  get_weather
-  icon=$(get_icon "$weather_icon")
-  desc=$(echo "$weather" | jq -r ".weather[0].description")
-  temp=$(echo "$weather" | jq ".main.temp" | cut -d "." -f 1)
-  humidity=$(echo "$weather" | jq ".main.humidity" | cut -d "." -f 1)
-  message="${desc} ${temp}°C ${HUMIDITY} ${humidity}%"
+function dwm_weather {
+    local icon desc temp humidity message
+    get_weather
+    icon=$(get_icon "$weather_icon")
+    desc=$(echo "$weather" | jq -r ".weather[0].description")
+    temp=$(echo "$weather" | jq ".main.temp" | cut -d "." -f 1)
+    humidity=$(echo "$weather" | jq ".main.humidity" | cut -d "." -f 1)
+    message="${desc} ${temp}°C ${HUMIDITY} ${humidity}%"
 
-  printf "%s" "$SEP1"
-  printf "%s" "$icon" "$message"
-  printf "%s\n" "$SEP2"
-  notification "$message" "$weather_icon"
+    printf "%s" "${SEP1:-}"
+    printf "%s" "$icon" "$message"
+    printf "%s\n" "${SEP2:-}"
+    notification "$message" "$weather_icon"
 }
 
-function bar_weather() {
-  local icon desc temp humidity message
-  get_weather
-  icon=$(get_icon "$weather_icon")
-  desc=$(echo "$weather" | jq -r ".weather[0].description")
-  temp=$(echo "$weather" | jq ".main.temp" | cut -d "." -f 1)
-  humidity=$(echo "$weather" | jq ".main.humidity" | cut -d "." -f 1)
-  message="${desc} ${temp}°C ${humidity}%"
+function bar_weather {
+    local icon desc temp humidity message
+    get_weather
+    icon=$(get_icon "$weather_icon")
+    desc=$(echo "$weather" | jq -r ".weather[0].description")
+    temp=$(echo "$weather" | jq ".main.temp" | cut -d "." -f 1)
+    humidity=$(echo "$weather" | jq ".main.humidity" | cut -d "." -f 1)
+    message="${desc} ${temp}°C ${humidity}%"
 
-  printf "%s" "$SEP1"
-  printf "%b%s°C %b %s%%" "$icon" "$temp" "$HUMIDITY" "$humidity"
-  printf "%s\n" "$SEP2"
+    printf "%s" "$SEP1"
+    printf "%b%s°C %b %s%%" "$icon" "$temp" "$HUMIDITY" "$humidity"
+    printf "%s\n" "$SEP2"
 }
 
 for cmd in "${DEPS[@]}"; do
-  if ! command -v "$cmd" >/dev/null; then
-    log_err "'$cmd' command not found."
-  fi
+    if ! command -v "$cmd" >/dev/null; then
+        log_err "'$cmd' command not found."
+    fi
 done
 
 if ! curl -Is "${API}" >/dev/null; then
-  log_err "weather API unreachable"
+    log_err "weather API unreachable"
 fi
 
 case "$1" in
