chore(bar): updates

diff --git a/bar/bar-battery b/bar/bar-battery
--- a/bar/bar-battery
+++ b/bar/bar-battery
@@ -1,10 +1,18 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 # Output: [ICON  98%]
 # Output: [ICON  98% status]
+#         
 #           
 #        
 #      
+#   
+#   
+# 
+
+PROG=$(basename "$0")
+BAT_CHARGE=$(cat /sys/class/power_supply/BAT0/capacity)
+BAT_STATUS=$(cat /sys/class/power_supply/BAT0/status)
 
 # notification icons
 warn="🔴"
@@ -13,25 +21,45 @@ icon_empty=""
 icon_low=""
 icon_mid=""
 icon_full=""
+icon_char=""
 
-bat_charge=$(cat /sys/class/power_supply/BAT0/capacity)
-bat_status=$(cat /sys/class/power_supply/BAT0/status)
-
-notification_critical() {
+function notification_critical() {
+	local hints critical_icon_noti
 	critical_icon_noti="battery-level-10-symbolic"
-	dunstify --urgency=critical -a "Battery" "Battery" "Battery critical: " -i "$critical_icon_noti" -h int:value:"$bat_charge" -h string:x-canonical-private-synchronous:battery
+	hints="string:x-canonical-private-synchronous:battery"
+
+  if ! command -v dunstify >/dev/null 2>&1; then
+    printf "%s: %s\n" "$PROG" "notify-send is not found"
+  fi
+
+	dunstify --urgency=critical -a "Battery" "Battery" "Battery critical: " -i "$critical_icon_noti" -h int:value:"$BAT_CHARGE" -h "${hints}"
 }
 
-get_icon() {
-	icon=""
+function is_charching() {
+	local bat_status
+	bat_status=$(cat /sys/class/power_supply/BAT0/status)
 
-	if [ "$bat_charge" -lt "20" ]; then
+	if [[ "${bat_status}" != "Charging" ]]; then
+		return 1
+	fi
+	return 0
+}
+
+function get_icon() {
+	local icon=""
+
+	if is_charching; then
+		echo "$icon_char"
+		return
+	fi
+
+	if [[ "$BAT_CHARGE" -lt "20" ]]; then
 		icon="$warn $icon_critical"
-	elif [ "$bat_charge" -lt "30" ]; then
+	elif [[ "$BAT_CHARGE" -lt "30" ]]; then
 		icon="$icon_empty"
-	elif [ "$bat_charge" -lt "50" ]; then
+	elif [[ "$BAT_CHARGE" -lt "50" ]]; then
 		icon="$icon_low"
-	elif [ "$bat_charge" -lt "90" ]; then
+	elif [[ "$BAT_CHARGE" -lt "90" ]]; then
 		icon="$icon_mid"
 	else
 		icon="$icon_full"
@@ -40,38 +68,14 @@ get_icon() {
 	echo "$icon"
 }
 
-dwm_battery() {
-	printf "%s" "$SEP1"
-	printf "%s  %s%% %s" "$(get_icon)" "$bat_charge" "$bat_status"
-	printf "%s\n" "$SEP2"
-}
-
-dwm_battery_color() {
-	empty_color="^c#cc241d^"
-	mid_color="^c#e78a4e^"
-	full_color="^c#9ECE6A^"
-	reset_color="^d^"
-
-	printf "%s" "$SEP1"
-	if [ "$bat_charge" -lt "30" ]; then
-		printf "%s%s %s %s%% %s" "$empty_color" "$icon_empty" "$reset_color" "$bat_charge" "$bat_status"
-	elif [ "$bat_charge" -lt "50" ]; then
-		printf "%s%s %s %s%% %s" "$empty_color" "$icon_low" "$reset_color" "$bat_charge" "$bat_status"
-	elif [ "$bat_charge" -lt "90" ]; then
-		printf "%s%s %s %s%% %s" "$mid_color" "$icon_mid" "$reset_color" "$bat_charge" "$bat_status"
-	elif [ "$bat_charge" -lt "95" ]; then
-		printf "%s%s %s %s%%" "$full_color" "$icon_full" "$reset_color" "$bat_charge"
-	elif [ "$bat_charge" -gt "95" ]; then
-		printf "%s%s %s %s%%" "$full_color" "$icon_full" "$reset_color" "$bat_charge"
+function main() {
+	if [ "$BAT_CHARGE" -lt 15 ]; then
+		notification_critical
 	fi
+
+	printf "%s" "$SEP1"
+	printf "%b %s%%" "$(get_icon)" " $BAT_CHARGE"
 	printf "%s\n" "$SEP2"
 }
-if [ "$bat_charge" -lt "15" ]; then
-	notification_critical
-fi
 
-if [ "$DWM_COLOR" = true ]; then
-	dwm_battery_color
-else
-	dwm_battery
-fi
+main
diff --git a/bar/bar-weather b/bar/bar-weather
--- a/bar/bar-weather
+++ b/bar/bar-weather
@@ -1,34 +1,28 @@
 #!/usr/bin/env bash
 
+PROG=$(basename "$0")
+DEPS=(jq curl)
+HUMIDITY=""
+#     
+
 # load envs
 # shellcheck source=/dev/null
-[ -f "$PRIVATE_ROOT"/openweather ] && . "$PRIVATE_ROOT"/openweather
+[[ -f "$PRIVATE_ROOT"/openweather ]] && source "$PRIVATE_ROOT"/openweather
 
-# Api
-key="$OPEN_WEATHERMAP_KEY"
-city="$OPEN_WEATHERMAP_CITY"
-units="metric"
-api="https://api.openweathermap.org/data/2.5"
+TOKEN="$OPEN_WEATHERMAP_KEY"
+CITY="$OPEN_WEATHERMAP_CITY"
+UNITS="metric"
+API="https://api.openweathermap.org/data/2.5"
+ICONS="$SCRIPTS/icons/weather/"
+GEOCLUE="https://location.services.mozilla.com/v1/geolocate?key=geoclue"
 
-# Icons
-icons="$HOME/.scripts/icons/weather/"
-
-check_dependencies() {
-	local dependencies program
-	program=$(basename "$0")
-	dependencies=(jq curl)
-
-	for cmd in "${dependencies[@]}"; do
-		if ! command -v "$cmd" >/dev/null; then
-			err_msg="'$cmd' command not found."
-			notification "$program script" "$err_msg"
-			title "$err_msg"
-			exit 1
-		fi
-	done
+function log_err() {
+	printf "%s: %s\n" "$PROG" "$@"
+	notify-send -i dialog-error-symbolic "$PROG" "$@"
+	exit 1
 }
 
-get_icon() {
+function get_icon() {
 	case $1 in
 	01d) icon="" ;;
 	01n) icon="" ;;
@@ -49,55 +43,89 @@ get_icon() {
 	echo "$icon "
 }
 
-get_weather() {
-	# TODO: Split...
-	if [ -n "$city" ]; then
-		if [ "$city" -eq "$city" ] 2>/dev/null; then
-			city_param="id=$city"
+function get_location() {
+	local location
+	location=$(curl -sf "$GEOCLUE")
+	if [[ -n "$location" ]]; then
+		location_lat="$(echo "$location" | jq '.location.lat')"
+		location_lon="$(echo "$location" | jq '.location.lng')"
+		weather=$(curl -sf "$API/weather?appid=$TOKEN&lat=$location_lat&lon=$location_lon&units=$UNITS")
+		weather_icon=$(echo "$weather" | jq -r ".weather[0].icon")
+	fi
+}
+
+function get_weather() {
+	# FIX: Split me...
+	if [[ -n "$CITY" ]]; then
+
+		# If is cityID
+		if [[ "$CITY" -eq "$CITY" ]] 2>/dev/null; then
+			city_param="id=$CITY"
 		else
-			city_param="q=$city"
+			city_param="q=$CITY"
 		fi
 
-		weather=$(curl -sf "$api/weather?appid=$key&$city_param&units=$units")
+		weather=$(curl -sf "$API/weather?appid=$TOKEN&$city_param&units=$UNITS")
 		weather_icon=$(echo "$weather" | jq -r ".weather[0].icon")
 	else
-		location=$(curl -sf https://location.services.mozilla.com/v1/geolocate?key=geoclue)
-		if [ -n "$location" ]; then
+		location=$(curl -sf "$GEOCLUE")
+		if [[ -n "$location" ]]; then
 			location_lat="$(echo "$location" | jq '.location.lat')"
 			location_lon="$(echo "$location" | jq '.location.lng')"
-			weather=$(curl -sf "$api/weather?appid=$key&lat=$location_lat&lon=$location_lon&units=$units")
+			weather=$(curl -sf "$API/weather?appid=$TOKEN&lat=$location_lat&lon=$location_lon&units=$UNITS")
 			weather_icon=$(echo "$weather" | jq -r ".weather[0].icon")
-			echo -e "$api/weather?appid=$key&lat=$location_lat&lon=$location_lon&units=$units"
+			echo -e "$API/weather?appid=$TOKEN&lat=$location_lat&lon=$location_lon&units=$UNITS"
 		fi
 	fi
 }
 
-send_notification() {
-	# FIX: Remove
-	curl -sd "$@" ntfy.sh/"$VOID_TOPIC" -o /dev/null
-}
-
-notification() {
+function notification() {
+	local date icon
 	date=$(date +"%a, %H:%M")
-	icon="${icons}${2}.png"
+	icon="${ICONS}${2}.png"
 	notify-send -i "$icon" "Weather $date" "$1"
 }
 
-dwm_weather() {
+function dwm_weather() {
+	local icon desc temp humidity message
 	get_weather
-  echo ">>$weather_icon"
 	icon=$(get_icon "$weather_icon")
 	desc=$(echo "$weather" | jq -r ".weather[0].description")
 	temp=$(echo "$weather" | jq ".main.temp" | cut -d "." -f 1)
 	humidity=$(echo "$weather" | jq ".main.humidity" | cut -d "." -f 1)
-	message="$desc $temp°C $humidity%"
+	message="${desc} ${temp}°C ${HUMIDITY} ${humidity}%"
 
 	printf "%s" "$SEP1"
 	printf "%s" "$icon" "$message"
 	printf "%s\n" "$SEP2"
-
 	notification "$message" "$weather_icon"
 }
 
-check_dependencies
-dwm_weather
+function bar_weather() {
+	local icon desc temp humidity message
+	get_weather
+	icon=$(get_icon "$weather_icon")
+	desc=$(echo "$weather" | jq -r ".weather[0].description")
+	temp=$(echo "$weather" | jq ".main.temp" | cut -d "." -f 1)
+	humidity=$(echo "$weather" | jq ".main.humidity" | cut -d "." -f 1)
+	message="${desc} ${temp}°C ${humidity}%"
+
+	printf "%s" "$SEP1"
+	printf "%b%s°C %b %s%%" "$icon" "$temp" "$HUMIDITY" "$humidity"
+	printf "%s\n" "$SEP2"
+}
+
+for cmd in "${DEPS[@]}"; do
+	if ! command -v "$cmd" >/dev/null; then
+		log_err "'$cmd' command not found."
+	fi
+done
+
+if ! curl -Is "${API}" >/dev/null; then
+	log_err "weather API unreachable"
+fi
+
+case "$1" in
+*notify) dwm_weather ;;
+*) bar_weather ;;
+esac
